### ISSUE TITLE
Imporvement: Add a possibility to query withRelated tables

### ISSUE THREAD

**Issue by zhanybek-sadvakassov** [AckeeCZ/databless#28]
Lets exepect that we have `users` table and `users_articles` tables, if i want to fetch user and specific user articles, i need to call 2 separate functions, but this can achieved by having `withRelated` property with some additional filter, it can look like following:
`userRepository.detail({ id: userId }, { withRelated: { articles: { isSpecial: true } } })`

**Comment by pavelsvagr** [comment]
You don't need to call two separate functions because knex supports this with injecting query builder: https://github.com/bookshelf/bookshelf/issues/361

We should update types for `withRelated`

**Comment by zhanybek-sadvakassov** [comment]
Thanks, that solves the issue 👍
